# Generated by Django 4.0.3 on 2022-05-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_user_name_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
    ]
