# Generated by Django 4.0.3 on 2022-05-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
    ]
