# Generated by Django 4.0.3 on 2022-05-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_users_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
